### ISSUE TITLE
Improve the usability of the OONI Probe Command Line Interface (CLI)

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1001]
To better support power users running OONI Probe on servers or interested in setting OONI Probe up on command line only systems, we will improve the usability of the OONI Probe CLI based on community feedback.

The OONI Probe CLI version 3.0.0 has been developed with the primary purpose of being used by the OONI Probe desktop app. As a result, it is not as rich as the (legacy python) OONI Probe 2.x command line interface, which was primarily developed for terminal users. 

By improving the usability of the OONI Probe CLI, we aim to ensure that the OONI Probe CLI 3.0.0 has feature parity with OONI Probe 2.0. Essentially, we aim to ensure that the new OONI Probe CLI has the same features as the python-based 2.x series of OONI Probe, while at the same time being based on an engine that allows for more in-depth network measurements.

As mentioned, the largest volume of stable OONI measurements has been collected from Linux users running OONI Probe 2.0. This command line version supported a number of very important features, which are currently missing from the new OONI Probe CLI. 

These missing features include:
Support for automatic daily testing (which is what led to the stable collection of measurements);
Ability to test custom lists of URLs;
Ability to run each OONI Probe test (from all available tests) separately.

The above important features are currently missing from the new OONI Probe CLI, which currently only includes the ability to:
Run all available OONI Probe tests;
Configure settings;
Opt-out from submitting measurements;
Opt-out from submitting certain types of data (ASN, country code, date and time of measurement).

We document a comparison of the difference between OONI Probe 3.0 (probe-cli) and OONI Probe 2.0 (probe-legacy) here. 

To support the Linux OONI community, we aim to achieve feature parity between OONI Probe 2.0 and the new OONI Probe CLI. This will not only enable Linux users to continue to contribute daily measurements from stable vantage points (thus supporting longitudinal research), but it will also enable them to configure and customize their testing based on their research and advocacy needs.

**Comment by hellais** [comment]
We have added support for the missing features since a while now.

Documenting them as part of this ticket:

* [x] Support for automatic daily testing (which is what led to the stable collection of measurements): https://github.com/ooni/probe-cli/pull/183
* [x] Ability to test custom lists of URLs: https://github.com/ooni/probe-cli/pull/180
* [x] Ability to run each OONI Probe test (from all available tests) separately: https://github.com/ooni/probe-cli/pull/206 (note: this currently requires miniooni)
* [x] Run all available OONI Probe tests; (available via miniooni)
* [x] Configure settings; (added support for this) https://github.com/ooni/probe-cli/blob/master/cmd/ooniprobe/internal/config/settings.go
* [x] Opt-out from submitting measurements; https://github.com/ooni/probe-cli/blob/master/cmd/ooniprobe/internal/config/settings.go#L5

Some things we implemented, but eventually decided to remove support for it in all app versions:
* Opt-out from submitting certain types of data (ASN, country code, date and time of measurement) (see for more context: https://github.com/ooni/probe/issues/1105)
