### ISSUE TITLE
Research using countly as a solution for push notifications

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1050]
* [x] Check if the count.ly UI allows us to set custom notification payloads
* [x] Make a prototype of the Probe Android app which uses count.ly for push notifications
* [x] Look into how we can leverage the count.ly plugin interface to make a custom OONI plugin for URL provisioning
* [x] Do extensive testing and ensure that we can do what we would to do using count.ly
* [x] Investigate if the community edition is enough or if we need to consider the enterprise version

**Comment by hellais** [comment]
We are going with countly! Yay!
