### ISSUE TITLE
Write OONI Probe experiments in Go

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1668]
Currently many the OONI Probe experiments are implemented inside of MeasurementKit: https://github.com/measurement-kit/measurement-kit/tree/master/src/libmeasurement_kit/nettests. There is also an implementation inside of the Probe Legacy implementation: https://github.com/ooni/probe-legacy/tree/master/ooni/nettests.

These are all specified inside of OONI Spec: https://github.com/ooni/spec/tree/master/nettests.

We should start porting these to golang in probe-engine. We will start with high priority tests (i.e. tests that are used by the mobile apps and will be used by the desktop app). We will also list some tests we may also wanna implement as less high priority tests. They are not used by the production apps but may be useful to run them manually sometimes.

The higher priority ones are are:

* [x] [dash](https://github.com/ooni/spec/blob/master/nettests/ts-021-dash.md)
* [x] [facebook-messenger](https://github.com/ooni/spec/blob/master/nettests/ts-019-facebook-messenger.md)
* [x] [header-field-manipulation](https://github.com/ooni/spec/blob/master/nettests/ts-006-header-field-manipulation.md)
* [x] [http-invalid-request-line](https://github.com/ooni/spec/blob/master/nettests/ts-007-http-invalid-request-line.md)
* [x] [ndt](https://github.com/ooni/spec/blob/master/nettests/ts-022-ndt.md)
* [x] [telegram](https://github.com/ooni/spec/blob/master/nettests/ts-020-telegram.md)
* [x] [web-connectivity](https://github.com/ooni/spec/blob/master/nettests/ts-017-web-connectivity.md) (this is pretty complex)
* [x] [whatsapp](https://github.com/ooni/spec/blob/master/nettests/ts-018-whatsapp.md)

Less high priority tests are:

* [ ] [captive-portal](https://github.com/ooni/spec/blob/master/nettests/ts-010-captive-portal.md)
* [ ] [dns-consistency](https://github.com/ooni/spec/blob/master/nettests/ts-002-dns-consistency.md)
* [ ] [dns-injection](https://github.com/ooni/spec/blob/master/nettests/ts-012-dns-injection.md)
* [ ] [http-post](https://github.com/ooni/spec/blob/master/nettests/ts-004-http-host.md)
* [ ] [dns-injection](https://github.com/ooni/spec/blob/master/nettests/ts-012-dns-injection.md)
* [ ] [meek-fronted-requests](https://github.com/ooni/spec/blob/master/nettests/ts-014-meek-fronted-requests.md)
* [ ] [tcp-connect](https://github.com/ooni/spec/blob/master/nettests/ts-008-tcp-connect.md)

Experiments that are not part of measurement-kit/measurement-kit or ooni/probe-legacy should go in separate issues.

**Comment by hellais** [comment]
I don't think we are going to after all implement the other older low priority tests. These tests are at this point deprecated and we should rather be focusing on next generation tests.

I suggest that in light of this we consider this issue closed and if we change our mind in the future we can always reopen a new issue.

**Comment by bassosimone** [comment]
I agree!
