### ISSUE TITLE
tor/torsf: next steps and methodology improvements

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1730]
This issue is an Epic issue collecting further improvements of the tor and torsf experiments. The content of this issue has been discussed yesterday with @cohosh. I am grouping all the content of the discussion together, so we have a single place to which we can refer when talking about the conversation we had. The general idea in moving forward is to create issues that belong to this Epic and start by fixing the easiest issues.

# Things to improve in the tor experiment

- [ ] no testing of fallback dirs
- [ ] the ciphersuites used for the TLS connections to OR ports might not match the ones Tor uses (this ClientHello fingerprinting is a well-established method to block Tor)
- [ ] clients with a live network-status document can also get the consensus from other v3 directory servers
- [ ] censors could also block tor by blocking all relays/guards in the consensus instead of blocking directory servers

# Things to improve in the torsf experiment

- [ ] figure out an easy way to collect logs that currently go on stdout
- [ ] see if we can define in `snowflake` an interface that gets called when specific events occur

**Comment by cohosh** [comment]
>  figure out an easy way to collect logs that currently go on stdout

I looked into this a bit, and there is a way with the current setup to control where the snowflake log output goes. We use the default logger for the Go standard library [log](https://pkg.go.dev/log) which sends messages to stderr by default. A quick fix for this might be to use the `SetOutput` function (available in Go versions 1.13 and later) allows you to set the output of the default logger to anything that implements the `io.Writer` interface. We do this ourselves in our main Snowflake program to [send logs through a log scrubber](https://pkg.go.dev/log).

However, my understanding is that this will send all output for all libraries that use the default logger to the same place.

**Comment by bassosimone** [comment]
This issue does not need to be an Epic because we already have an Epic on ~this topic (https://github.com/ooni/probe/issues/1686) and it does not help us to have duplicate issues.

**Comment by bassosimone** [comment]
@cohosh thank you for looking into this! I will take a look at whether this is a feasible approach for us, but the fact that every user of `log.Printf` goes into the same redirected writable may indeed be an issue for us!

**Comment by bassosimone** [comment]
I am going to transform this issue into an Epic and move sub-issues that were part of https://github.com/ooni/probe/issues/1657 to this issue, since this issue basically contains everything we'd like to do next for tor experiments.
