### ISSUE TITLE
cli: release 3.13

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1843]
This issue derives from https://github.com/ooni/probe/issues/1506. We have figured out that the routine releases model does not serve us well when we have longer release cycles (which we have now). Hence I am spawning off this issue of https://github.com/ooni/probe/issues/1506.

The check-list below derives from https://github.com/ooni/probe/issues/1815, which contained the check-list for https://github.com/ooni/probe/issues/1506.

# Check list

- [x] psiphon: run ./update.bash
- [x] ooni/go: merge with upstream if needed
- [x] oohttp: merge with upstream if needed
- [x] probe-cli: update the version of go used by github actions
- [ ] probe-cli: take a look at [go report card](https://goreportcard.com/report/github.com/ooni/probe-cli)
- [ ] probe-cli: address any outstanding TODO in the diff since last release (or create an issue for it)
- [x] probe-cli: ensure `./mk` is using latest version of several tools
- [x] probe-cli: update github.com/ooni/probe-assets dependency
- [x] probe-cli: update dependencies
- [x] probe-cli: update internal/engine/httpheader/useragent.go
- [x] probe-cli: update internal/version/version.go
- [x] probe-cli: update bundled certs (using `go generate ./...`)
- [ ] probe-cli: make sure all workflows are green
- [ ] probe-cli: `go test -race -count 1 ./...` must pass locally
- [ ] probe-cli: tag a new version
- [x] probe-cli: update internal/version/version.go to be alpha
- [ ] probe-cli: create release at GitHub
- [ ] probe-android: pin to latest oonimkall
- [ ] probe-ios: pin to latest oonimkall
- [ ] probe-desktop: pin to latest cli
- [ ] probe: create issue for next routine release
- [ ] e2etesting: see whether we can remove legacy checks

**Comment by bassosimone** [comment]
Changed the title: I did a mistake and pushed an `-alpha` build for Debian. So, I need to tag `3.13` to undo this mistake.

**Comment by bassosimone** [comment]
This epic should have been closed in the previous Sprint. I have just migrated all the issues that belonged to it to the next release and I am closing it now.
