### ISSUE TITLE
cli: continuous delivery with psiphon config and notarization

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1880]
The current build process (as of v3.12.0-alpha.2 / 3.11.0-beta.1) does not include the psiphon configuration file into the build when building inside of GitHub actions. Additionally, the produced binaries are not signed or notarised. Therefore, they do not work on Windows and macOS. (With both, probably a user can force Windows to run them anyway, but this is sub-optimal.) To include the psiphon configuration file, we're currently running builds on a local system. Additionally, we are not automatically publishing Android libraries to Maven central. Also this step is run manually.

In short, we are lacking a robust continuous delivery process for ooni/probe-cli (and, to some extent, ooni/probe-destktop). This situation is sad, because we are wasting time running manual commands that we could use for more fundamental tasks.

I prepared an internal design document explaining the situation and providing solutions. We discussed this design document with @hellais, @FedericoCeratto, and @sarathms. We explored several possibilities.

This issue roughly documents what seems the best solution for us:

- [x] include the psiphon configuration as a secret for the ooni/probe-cli build
- [x] use such a secret when producing binaries
- [x] modify build rules to publish binaries inside releases
- [x] write new tool/repository that "amends" a release
- [ ] ensure each rule for producing a release build includes smoke tests

Specifically, amending a release means performing the following activities:

1. fetching all binaries generated by an existing release
2. notarising macOS binaries and uploading them again to the release
3. signing Windows binaries and uploading them again to the release
4. fetching Android libs, sign them, and upload to Maven central
5. publishing the relevant Debian packages to our repo

Obviously, all this work requires some restructuring the build scripts, GitHub actions, and the docs. Yet, it seems doing this work is worth it, because it will significantly increase our confidence that we're correctly releasing.

We want to implement this set of activities for release/3.11 (currently in beta) and release/3.12 (currently in alpha).

Because this set of activities is not small, I'm going to convert this issue into an Epic.

**Comment by bassosimone** [comment]
I am going to close this issue now. Here are my thoughts regarding this experiment. It certainly improved upon the previous situation. We are still unhappy because we would like to first QA binaries and then publish releases, not the other way around. Another pain point is that each build proceeds on its own, and each of them may fail. To reduce the number of failure modes, and to perform QA before publishing, we probably need another design. This design really looks like a dedicated runner (perhaps hosted on our infrastructure) that builds all the required binaries, performs QA checks, and then deems a release good to go. It will take some time to figure out exactly how this magical box for making releases better would work. In the meanwhile, the code and solutions developed as part of this issue will do. Yet, I don't think we should invest extra effort to go down in this direction, rather we should steer towards a more unified way of producing builds. This reckoning is what ultimately informs my decision of closing this issue for good.
