### ISSUE TITLE
cli: release 3.14.2

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#2067]
This patch release will update dependencies and fix builds using go1.18 (see https://github.com/ooni/probe/issues/2066)

# Tasks

- [x] psiphon: run ./update.bash
- [x] oohttp: merge with upstream if needed
- [x] ooni/go: merge with upstream if needed
- [x] probe-cli: update the version of go used by github actions
- [x] probe-cli: update dependencies with `go get -u -v -d ./...`
- [x] probe-cli: update internal/engine/httpheader/useragent.go
- [x] probe-cli: update internal/version/version.go
- [x] probe-cli: update github.com/ooni/probe-assets dependency
- [x] probe-cli: update bundled certs (using `go generate ./...`)
- [x] probe-cli: tag a new version
- [x] probe-cli: create release at GitHub

**Comment by bassosimone** [comment]
All done!
