### ISSUE TITLE
Release 3.15 checklist

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#2100]
- [x] psiphon: run ./update.bash
- [x] ooni/go: merge with upstream if needed
- [x] oohttp: merge with upstream if needed
- [ ] ooni/go-libtor: update
- [ ] probe-cli: sync stunreachability targets with snowflake (see `./internal/stuninput`)
- [x] probe-cli: update the version of go used by github actions
- [x] probe-cli: take a look at [go report card](https://goreportcard.com/report/github.com/ooni/probe-cli)
- [ ] probe-cli: address any outstanding TODO in the diff since last release (or create an issue for it)
- [x] probe-cli: ensure `./mk` is using latest version of several tools
- [x] probe-cli: ensure github.com/bassosimone/monorepo is using the latest version of several tools
- [x] probe-cli: update dependencies with `go get -u -v -d ./...`
- [ ] probe-cli: ensure no dependency bumped its major version number
- [x] probe-cli: update internal/engine/httpheader/useragent.go
- [x] probe-cli: update internal/version/version.go
- [x] probe-cli: update github.com/ooni/probe-assets dependency
- [x] probe-cli: update bundled certs (using `go generate ./...`)
- [ ] probe-cli: make sure all workflows are green
- [x] probe-cli: `go test -race -count 1 ./...` must pass locally
- [x] probe-cli: tag a new version
- [x] probe-cli: update internal/version/version.go to be alpha
- [x] probe-cli: create release at GitHub
- [x] probe-android: pin to latest oonimkall
- [x] probe-ios: pin to latest oonimkall
- [x] probe-desktop: pin to latest cli
- [x] probe: create issue for next routine release

**Comment by bassosimone** [comment]
Created next release's check-list here https://github.com/ooni/probe/issues/2130. I feel it's okay to close this issue currently. As regards the items we did not complete:

* ooni/go-libtor: update
* probe-cli: sync stunreachability targets with snowflake (see ./internal/stuninput)

These two were both updated recently, we'll update them again in the next release cycle.

*  probe-cli: address any outstanding TODO in the diff since last release (or create an issue for it)

This one was not done.

*  probe-cli: make sure all workflows are green

The QA workflows are flaky. I think we need to improve how we run QA to address this fundamental issue.
