### ISSUE TITLE
ooniprobe-cli v3.23 release process

### ISSUE THREAD

**Issue by DecFox** [ooni/probe#2783]
## Release information

Fill out this information for each release:

**Version Number:** 3.23.0

**Expected Release date:** Aug 7, 2024

**Summary of changes:**

- changes to begin introducing richer-input
- maintenance changes

**Link to latest nightly:**  https://github.com/ooni/probe-cli/releases/tag/rolling

## Release checklist

For extended documentation about the process, see [probe-cli's releasing.md](https://github.com/ooni/probe-cli/blob/master/docs/releasing.md).

### Psiphon

- [x] probe-cli: pin to the latest [staging-client commit](https://github.com/Psiphon-Labs/psiphon-tunnel-core/tree/staging-client) using `./script/go.bash get -u -v`: https://github.com/ooni/probe-cli/pull/1642
- [x] probe-cli: make sure `./script/go.bash list -json ./cmd/ooniprobe` does not include any pinned package in psiphon's `go.mod` or otherwise ask Psiphon developers whether this is fine: https://github.com/ooni/probe-cli/pull/1642, checked locally.

### Go version

- [x] oocrypto: merge with upstream if needed: https://github.com/ooni/oocrypto/pull/29, https://github.com/ooni/probe-cli/pull/1645
- [x] oohttp: merge with upstream if needed: https://github.com/ooni/oohttp/pull/65, https://github.com/ooni/probe-cli/pull/1645
- [x] probe-cli: possibly update `.github/workflows/gobash.yml`: not required
- [x] probe-cli: update the `GOVERSION` file if needed: https://github.com/ooni/probe-cli/pull/1645
- [x] probe-cli: update the `toolchain` line inside of `go.mod`: https://github.com/ooni/probe-cli/pull/1645
- [x] probe-cli: update the Go version mentioned in the `Readme.md` file: https://github.com/ooni/probe-cli/pull/1645
- [x] probe-cli: update version specified in TH's Makefile: https://github.com/ooni/probe-cli/pull/1645

### Android

- [x] probe-cli: update `NDKVERSION`, and `MOBILE/android/ensure` if needed: https://github.com/ooni/probe-cli/pull/1643

### Dependencies other than Psiphon

- [x] probe-cli: ensure no dependency bumped its major version number using https://github.com/icholy/gomajor: https://github.com/ooni/probe-cli/pull/1646
- [x] probe-cli: update dependencies with `./script/go.bash get -u -v -d ./...`: https://github.com/ooni/probe-cli/pull/1646
- [x] probe-cli: update C dependencies: https://github.com/ooni/probe-cli/pull/1644

### Updating assets and definitions

- [x] probe-cli: run `./script/updateminipipeline.bash`: https://github.com/ooni/probe-cli/pull/1647
- [x] probe-cli: update github.com/ooni/probe-assets dependency: https://github.com/ooni/probe-cli/pull/1647
- [x] probe-cli: update bundled certs (using `./script/go.bash generate ./...`): https://github.com/ooni/probe-cli/pull/1647
- [x] probe-cli: update user-agent at `internal/model/http.go`: https://github.com/ooni/probe-cli/pull/1647

### Maintenance

- [x] probe-cli: sync stunreachability targets with snowflake (see `./internal/stuninput`)
- [x] probe-cli: take a look at [go report card](https://goreportcard.com/report/github.com/ooni/probe-cli/v3)
- [x] all: check whether to update the release documentation: not required
- [x] probe-cli: address any outstanding TODO in the diff since last release (or create an issue for it): done
- [x] probe-cli: try to address all the issues marked as "releaseBlocker"

### QA and alpha releasing

- [x] probe-cli: check warnings emitted by `gosec` runs: https://github.com/ooni/probe-cli/pull/1648
- [x] probe-cli: `./script/go.bash test -race -count 1 ./...` must pass locally: There are failing tests due to: https://github.com/ooni/devops/issues/86, but local tests pass for the prod host. 
- [x] probe-cli: tag an alpha release: https://github.com/ooni/probe-cli/releases/tag/v3.23.0-alpha
- [x] probe-cli: create the release/X.Y branch: https://github.com/ooni/probe-cli/tree/release/3.23
- [x] probe-cli: make sure all workflows are green in the release/X.Y branch: The failing tests are unrelated to the engine and have been documented to be fixed for the infra.
- [x] team: communicate availability of an alpha release

### Releasing proper

- [x] probe-cli: update `internal/version/version.go` in release/X.Y to be a stable release: https://github.com/ooni/probe/issues/2783#issue-2432230147
- [x] probe-cli: tag a new stable version in the release/X.Y branch: https://github.com/ooni/probe/issues/2783#issue-2432230147
- [x] probe-cli: update internal/version/version.go in master branch to be the next alpha: https://github.com/ooni/probe-cli/pull/1650

### Publishing stable packages

- [x] probe-engine: run `./script/autoexport.bash`: https://github.com/ooni/probe-engine/pull/1211
- [x] android: publish packages: https://s01.oss.sonatype.org/content/repositories/releases/org/ooni/oonimkall/2024.08.08-091959/, https://repo.maven.apache.org/maven2/org/ooni/oonimkall/2024.08.08-091959/
- [x] debian: publish packages

## Post-release communication 

- [ ] iThena: notify about new release
