### ISSUE TITLE
Add tcp_connect tests for Tor directory authorities and Tor Browser bridges

### ISSUE THREAD

**Issue by akwizgran** [ooni/probe#802]
It would be useful to have data about which networks block TCP connections to the Tor directory authorities and well-known bridges, such as those bundled with the Tor Browser.

The output from these tests would help the [Briar project](https://code.briarproject.org/briar) to maintain lists of countries where different methods of connecting to the Tor network (e.g. direct connection, vanilla bridges, obfs4 bridges) are likely to succeed. The Briar app uses these lists to choose a default connection method based on the user's location. The Briar devs are hoping to find volunteers to collect this data in censored countries and contribute it to OONI, and since our users are Android users it would be great if the Ooniprobe Android app supported these tests.

If I understand right, the tcp_connect test already exists in the version of Measurement Kit used by the Android app, and the data for these tests will be made available from the orchestrator (https://github.com/ooni/orchestra/issues/51).

**Comment by hellais** [comment]
What would need to happen to make this become a reality is the following (these don't necessarily have to be done in this order):

* [ ] The UX items in https://github.com/ooni/probe/issues/804 are done
* [ ] ooni/orchestra supports giving out bridge addresses: https://github.com/ooni/orchestra/issues/51 
* [ ] either a new test or some adaptation of tcp_connect is done which speaks to ooni/orchestra to retrieve bridge addresses to test and runs the test
* [ ] The rest of the items listed in https://github.com/ooni/probe/issues/804 specific to new test development

**Comment by hellais** [comment]
I suspect this may be a duplicate of other existing issues. We are getting very close to being able to do this.

**Comment by bassosimone** [comment]
Correct, this is what the new tor experiment is enabling us to do: https://github.com/ooni/probe-engine/issues/226

**Comment by bassosimone** [comment]
@hellais I would like to close this issue, any objections?

**Comment by hellais** [comment]
This has been completed as part of: https://github.com/ooni/orchestra/issues/82
