### ISSUE TITLE
Single-measurement submission

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#863]
As said in #861, the [single measurement upload (SMU) flow](https://github.com/ooni/spec/blob/master/backends/bk-003-collector.md#34-submitting-single-measurements-using-a-single-api-call), could significantly cut the duration of resubmission. The following check-list, updated to also account for https://github.com/ooni/backend-legacy/pull/124#issuecomment-502656910, describes the steps to make make this possible:

- [x] research the complexity of implementing the SMU flow in ooni/backend-legacy and decide whether this is worth the effort. Conclusion: it was easy, fully functioning client and server side prototype written in little more than one hour. See #122.

- [x] implement the SMU flow in ooni/backend-legacy. See: https://github.com/ooni/backend-legacy/pull/124.

- [ ] A new VM is created where we'll deploy testing collector code. See https://github.com/ooni/sysadmin/issues/330

- [ ] A new docker image is created from https://github.com/ooni/backend-legacy/pull/124 without merging that PR into master (we don't want to actually merge it, as there is rough consensus that working on this feature is also a chance to finish off the new `ooni/collector`)

- [ ] Said image is deployed to a testing machine, perhaps `amstestcollector.ooni.nu`

- [ ] implement the SMU flow in ooni/probe-engine using the above testing machine. See: https://github.com/ooni/probe-engine/pull/21.

- [ ] implement the SMU flow in measurement-kit/mkcollector using the above testing machine.

- [ ] implement the SMU flow in ooni/collector. To do this, we need to take a little detour and land https://github.com/ooni/collector/pull/3 into master. The functionality is actually already implemented in there IIUC, however, without merging to master we cannot access it, of course.

- [ ] We deploy ooni/collector on `a.collector.ooni.io` and start trying it out with a subset of the clients and check if it works with the pipeline

- [ ] `amstestcollector.ooni.nu` is decommissioned

- [ ] We implement the measurement_id feature in ooni/collector as per the spec

- [ ] make sure the clients and the server work together

- [ ] We roll this out in production and start using it for `b.collector`

- [ ] We decide what to do with `a.collector` (my proposal would be to keep it as the piece of metal running the next version of the collector code, while `b.` and `c.` are more stable)

- [ ] More testing and assurance that nothing breaks

Note: the above proposal of using `a.collector` is reasonable because `a.collector` has not been receiving reports for months now, and is not announced by the bouncer.

**Comment by hellais** [comment]
This got interrupted to avoid implementing it in the legacy collector and ended up implementing a different strategy using MK changing the way we submit to re-use connections.

See: https://github.com/ooni/probe/issues/861

**Comment by bassosimone** [comment]
It seems we don't want to do this, but rather we want to use check-in to fetch the report IDs along with other information, and then we already have the report ID to submit. We anyway already reduced the complexity of submitting measurements because we have removed the requirement to close a report.
