### ISSUE TITLE
Re-add automatic daily testing

### ISSUE THREAD

**Issue by hellais** [ooni/probe#916]
We should re-add the feature for doing automatic daily testing.

The MVP is that of doing automatic testing (websites) on a daily basis at a specified time.

Settings:
- Wifi Only [DEFAULT NOT EDITABLE]
- Charging only [DEFAULT NOT EDITABLE]
- Run the service every hour, randomized by the time the user enable
- Test duration should be controlled from the backend
- Add analytics to know how many people enabled it

In the future we may want to provide more configuration options to the user, namely:
- Enable more tests types
- Setting data usage caps:
- Monthly mobile allowance
- Monthly WiFi allowance

cc @lorenzoPrimi @bassosimone

**Comment by hellais** [comment]
Closing the other issue, but copying the comment from @agrabeli  in here (https://github.com/ooni/probe/issues/917#issuecomment-575750386):
> Sorry, I commented without having read my own text above and I misunderstood. While what you implemented is fantastic (i.e. having the ability to disable max runtime in the app), this issue is a bit different: it requests the automated testing of the full test list. Essentially, once Automated testing is re-introduced to the app, then it's a question of adding support for the automated testing of the full test list (without requiring users to know to manually disable the max runtime).

**Comment by lorenzoPrimi** [comment]
Default settings:
Time 05:00
WiFiOnly Yes
MaxRuntimeEnabled No
MaxRuntime 90

**Comment by lorenzoPrimi** [comment]
UPDATE:
apparently in my brand new shiny Android phone I can't run the `RunningActivity` from a service in background
```
2020-10-15 14:15:52.250 1561-1615/? D/com.android.server.am.ExtraActivityManagerService: MIUILOG- Permission Denied Activity : Intent { flg=0x10000000 cmp=org.openobservatory.ooniprobe.dev/org.openobservatory.ooniprobe.activity.RunningActivity (has extras) } pkg : org.openobservatory.ooniprobe.dev uid : 10261 tuid : 10060
```
xRef: https://stackoverflow.com/questions/56295901/miui-permission-denied-activity-keyguardlocked

All permissions were given: https://c.mi.com/forum.php?mod=viewthread&tid=2871872&aid=5514697&from=album&page=1

**Comment by bassosimone** [comment]
@lorenzoPrimi wrote:

> Time 05:00

Please, don't. Synchronising the moment in which the probes within a timezone start a background experiment hampers future scalability and is a constant threat for our infrastructure, that is forced to handle impulsive inputs.

We don't want to give too much control to users here, because too much users control means too little coordination until we have a backend that can choose how many measurements it wants a user to run "now" in country X and network Y.

Let us instead spread the load caused by the probes across a time span that covers a few hours. I have a specific soapbox on how the scheduling function should be structured, but I have also seen simpler scheduling functions "work".

If 5:00 is AM, then I just propose we choose a moment a random during the night, where the phone is docked and attached to Wi-Fi. We loose measurements from people like me, who put the phone in flight mode at night, but metrics will help us understand whether this is a big problem or not.

If 5:00 is PM, then we should probably randomise the starting moment during the evening. (In a bunch of places 5:00 PM is commute time, so I am not sure this will fit well with the attached-to-Wi-Fi requirement?)

> In alternative we can run the test silently like we do in the integration test, the only downside of this is that if the user opens the app won't see the test running screen

Since this is a background feature, I think we are safe as long as we can tell the user with an Activity that a background test is already running if they open the app when a background test is running. Because they open the app, it seems to me they are quite logically launching an Activity. So my question is whether this activity could learn about a background test.

Speaking of background tests, it worries me that adding such tests we could also enable concurrent background and foreground tests, which is something we really do not want for a bunch of reasons. I can add specific support in probe-engine for this functionality, but in the next release perhaps.

**Comment by lorenzoPrimi** [comment]
The problem with the "background feature" is being able to tell the user there is a test running if he opens the app and I'm not sure this is possible or easy.
But at the same time we want to prevent the user to another test if one is running.
If there would be a way to ask the Engine "is a test running?" that would solve a lot of headaches

**Comment by bassosimone** [comment]
@agrabeli:

> I think the idea of having a specified time during which probes run tests (and that that time is early in the morning) was inspired by Lepidopter, which was configured to run tests automatically everyday at 6am (local time).

Happy to hear this runs during the night. I was unsure whether 5 was AM and PM. And I like AM much more.

> I think the main issue [...] is whether and to what extent our infrastructure will be able to handle such a large volume of incoming measurements, once automated testing is enabled.

I would encourage us to ask another question. That is, whether the proposed design could hamper future growth. The answer is that we could tune the backend to resist to our current population of clients all connecting together. This requires human engineering effort. What's more, if the population of users slowly increases, this eventually becomes critical and could be damaging our infrastructure. While I concur that our future population of clients should not change dramatically, I also think that the design of a system should not make too optimistic assumption.

> For example, would it be possible to store measurements coming from "automated testing" (this would require some sort of tagging) in a separate bucket, so that if we see that we are "flooding in measurements", we can at least store them as a short-term solution (until they're processed and published)?

Yes, this could be possible. The question I have is why dimensioning our system to resist a flood when we can change the design of the probes to avoid artificially creating the flood int he first place.

To avoid creating such a potential flood, we just need a little tweak. Let the option be "run tests tonight when connected to Wi-Fi" and then just randomise a random second between 2 AM and 6 AM where to start the measurement.

This design is still not optimal in terms of absolute scalability, but I have seen people using this design without creating too much load to large infrastructure up until a client population that is ~100x our current one.

> What changes do we need to make to our backend infrastructure in order to accommodate increased collection of measurements?

I would encourage us to ask the opposite question: what changes can we make to our distributed probes to avoid investing extra efforts, spending extra money, generating extra work for whoever is managing the backend?

I would also recommend to think in terms of fragility. Our system would be less fragile if probes distribute their tests during the night. Conversely, it becomes more fragile if the backend becomes more susceptible to a fluctuation in the population of users. I would argue that we want to reduce fragility and the human cost spent on the backend.

> As for randomized testing => Perhaps we could inform this based on our existing knowledge of the volume of measurements we expect to receive per country?
>
> For example, we know that we regularly receive a large volume of measurements from the USA, but we receive a small volume of measurements from Somalia. Perhaps we can distribute the testing load based on the volume of measurements that we expect to receive per country?
>
> This though sounds like it would require some backend work.

I concur that we should not be doing anything smart with work allocations until the backend is able to provide users with specially tailored test lists that depend on the context. This is particularly insightful because the population of users may change and we should not make our design more fragile than needed by assuming it won't change.

Thanks for the conversation!

**Comment by bassosimone** [comment]
> If there would be a way to ask the Engine "is a test running?" that would solve a lot of headaches

There is a definitely a way in which we could make this happen.

**Comment by lorenzoPrimi** [comment]
Updates:
I've been testing intensively the background test implementation, stressing my phone.
But most of the times I would get Error, a few times I got the test results.
I re-engineered the current code but at the end I never got anything close than 90% tests ran.
I noticed that when the debugger was connected the test would always run, when the phone was like "sleeping" the test would fail.
Fail to geolocate, to download URLs, and to run.

`
2020-10-22 12:26:20.162 19878-12882/org.openobservatory.ooniprobe.dev W/System.err: org.openobservatory.engine.OONIException: session.geolocate failed
`

`
2020-10-22 12:26:20.285 19878-12882/org.openobservatory.ooniprobe.dev D/OkHttp: <-- HTTP FAILED: java.io.IOException: unexpected end of stream on https://orchestrate.ooni.io/...
2020-10-22 12:26:20.287 19878-12882/org.openobservatory.ooniprobe.dev W/System.err: java.io.IOException: unexpected end of stream on https://orchestrate.ooni.io/...
`

AH HA, the network is down! 
Or at least is not working from the `AlarmReceiver`

Our system maybe worked in the past, but don't work with the newer Android as they changed some services: 
`note that when the app is in the background ,specifically for android api 26>= background service might be destroyed or network connection might disconnect`


Starting the `RunningActivity` is not possible anymore (even if it was a working approach on older versions) as we need to involve the user asking permissions manually, and we want to keep it more simple.
And also we want to start a test in background not an activity with all the related UI stuff.
 
More research about background scheduler is needed:
https://www.bignerdranch.com/blog/choosing-the-right-background-scheduler-in-android/

**Comment by lorenzoPrimi** [comment]
`AlarmManager` will be removed
`Sync Adapter` and `Doze mode` are not what we are looking for

`JobScheduler `is the way to go!
JobScheduler provides efficient background scheduling, but only if your user is running API level 21 or higher

https://www.vogella.com/tutorials/AndroidTaskScheduling/article.html

**Comment by lorenzoPrimi** [comment]
We might want to reimplement the test as a "Foreground service" that lives in the notification centre.
With a stop button maybe.
![unnamed.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/a59350c8-97e0-431a-98a0-3f84a48d1831)

**Comment by lorenzoPrimi** [comment]
The first version of "Test as a service" has been implemented, these are the remaining steps

- [ ] start cleaning the code
- [ ] add STOP action in the notification
- [ ] TODOs in the code
- [ ] run the test more times in row, stress the app
- [ ] Start the test from background with the automation
- [ ] connect RunningActivity to the RunTestService

**Comment by lorenzoPrimi** [comment]
Options we can consider for the future:

```
//job will fire after 5 seconds when the network becomes available, or no later than 5 minutes
//Specify that this job should be delayed by the provided amount of time.
builder.setMinimumLatency(5 * 1000); // wait at least
```
setMinimumLatency(long minLatencyMillis): This makes your job not launch until the stated number of milliseconds have passed. This is incompatible with setPeriodic(long time) and will cause an exception to be thrown if they are both used.


```
//the job will be executed anyway after 5 minutes waiting
//Set deadline which is the maximum scheduling latency.
builder.setOverrideDeadline(5 * 60 * 1000); // maximum delay
```
setOverrideDeadline(long maxExecutionDelayMillis): This will set a deadline for your job. Even if other requirements are not met, your task will start approximately when the stated time has passed. Like setMinimumLatency(long time), this function is mutually exclusive with setPeriodic(long time) and will cause an exception to be thrown if they are both used.

```
builder.setPersisted(true); //Job scheduled to work after reboot
```
setPersisted(boolean isPersisted): This function tells the system whether your task should continue to exist after the device has been rebooted.

setRequiredNetworkType(int networkType): This function will tell your job that it can only start if the device is on a specific kind of network. The default is JobInfo.NETWORK_TYPE_NONE, meaning that the task can run whether there is network connectivity or not. 
The other two available types are JobInfo.NETWORK_TYPE_ANY, which requires some type of network connection available for the job to run, and JobInfo.NETWORK_TYPE_UNMETERED, which requires that the device be on a non-cellular network.

setRequiresCharging(boolean requiresCharging): Using this function will tell your application that the job should not start until the device has started charging.

setRequiresDeviceIdle(boolean requiresDeviceIdle): This tells your job to not start unless the user is not using their device and they have not used it for some time.

```
builder.setPeriodic(30 * 60 * 1000);
```
Minimum flex for a periodic job, in milliseconds.
//http://androidxref.com/8.0.0_r4/xref/frameworks/base/core/java/android/app/job/JobInfo.java#110

**Comment by lorenzoPrimi** [comment]
Last steps:
- [ ] Disable UI Blocked when automatic test ran
- [ ] Not save any data in the database when auto test is running
- [ ] Save basic details as last_run_time, number of test ran
